services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /opt/compose/arr-stack/radarr:/config
      - /mnt/das/data/Movies:/movies
      - /mnt/das/data/completed:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /opt/compose/arr-stack/sonarr:/config
      - /mnt/das/data/TV Shows:/tv
      - /mnt/das/data/Kids TV:/kids-tv
      - /mnt/das/data/completed:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Denver
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /opt/compose/arr-stack/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /opt/compose/arr-stack/bazarr:/config
      - /mnt/das/data/TV Shows:/tv
      - /mnt/das/data/Kids TV:/kids-tv
      - /mnt/das/data/Movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
